
version: '3.9'

services:
  aiartcontainer:
    ports:
      - "443:7860"
    container_name: "aiartcontainer"
    image: aiart:stablediffusion
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
    stop_signal: SIGINT
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api
