# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chanbull-aiart-web

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_bd25ae6e62f2445896a111b31b3df1d5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3fd55b66f7b54f908bbe34396ce3c049 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bd25ae6e62f2445896a111b31b3df1d5 }}/aiart:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chanbull-aiart-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6b16c15af7da4d89939a8e393822eb1a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bd25ae6e62f2445896a111b31b3df1d5 }}/aiart:${{ github.sha }}'